### ISSUE TITLE
The parameter settings for SD reconstruction

### ISSUE THREAD

**Issue by taoxinhao13** [beibuwandeluori/DRCT#1]
Great work! Could you please share the details of your parameter settings when using the SD model for reconstruction? For example, the prompt, denoising strength and guidance scale?

**Comment by beibuwandeluori** [comment]
Thank you for your interest in our paper.“SDv1-DR”, “SDv2-DR”, and “SDXL-DR” are utilized to generate reconstruction images of the real images using the SD inpainting models (such as " runwayml/ stable-diffusion-inpainting"), with input conditions being the image, text prompt, and binary mask, where the input image comes  from the real image in MSCOCO, the prompt is an empty string “”, and the mask is a zero matrix of the same size as the real image.
Moreover, the values of guidance scale and other parameters are using the default values in diffusers.StableDiffusionInpaintPipeline or diffusers. AutoPipelineForInpainting.

---Original---
From: ***@***.***&gt;
Date: Thu, Jul 4, 2024 10:46 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [beibuwandeluori/DRCT] The parameter settings for SD reconstruction(Issue #1)




 
Great work! Could you please share the details of your parameter settings when using the SD model for reconstruction? For example, the prompt, denoising strength and guidance scale?

**Comment by taoxinhao13** [comment]
Sorry if my previous question caused any confusion. What I meant was whether the paper used the above "runwayml/stable-diffusion-inpainting" and its corresponding default parameters for reconstruction during training on gen-image(sd1.4)? Thank you very much for your answer!

**Comment by taoxinhao13** [comment]
Because in my understanding, if the mask a zero matrix, it actually only goes through the VAE process, and the noising/denoising process does not participate at all; while if the mask is all ones and uses the default parameters, the denoising result will be completely independent of the input image. I feel that both of these settings are quite confusing.

**Comment by beibuwandeluori** [comment]
Maybe you can add my Wechat "BoykingChen" for more discussion. Thanks!
